const englishProductTitles: Record<string, string> = {
  "Sitzobjekt aus europäischem Kuhfell": "Sculptural Seat in European Cowhide",
  "Sitzobjekt aus dunklem Holz": "Dark Wood Seating Object",
  "Niedrige Bank aus Eiche": "Low Oak Bench",
  "Sessel mit Lederauflage": "Armchair with Leather Overlay",
  "Konsole aus geräuchertem Holz": "Smoked Wood Console",
  "Tisch mit Steinplatte": "Table with Stone Top",
  "Regalobjekt aus Nussbaum": "Walnut Shelf Object",
  "Daybed mit Wollbezug": "Daybed with Wool Cover",
  "Hocker aus massivem Holz": "Solid Wood Stool",
  "Schreibtisch mit klarer Kante": "Desk with Clean Edge",
  "Sideboard mit Steinauflage": "Sideboard with Stone Top",
  "Stuhl mit Stahlrahmen": "Chair with Steel Frame",
  "Runder Tisch aus Esche": "Round Ash Table",
  "Leuchte aus Bronze": "Bronze Light",
  "Wandleuchte mit Glasschirm": "Wall Light with Glass Shade",
  "Tischleuchte aus Stahl": "Steel Table Lamp",
  "Stehleuchte mit Stoffschirm": "Floor Lamp with Fabric Shade",
  "Pendelleuchte aus Messing": "Brass Pendant Light",
  "Keramische Wandlampe": "Ceramic Wall Lamp",
  "Lichtobjekt aus Glas": "Glass Light Object",
  "Deckenleuchte mit Bronzedetail": "Ceiling Light with Bronze Detail",
  "Kleine Tischleuchte aus Stein": "Small Stone Table Lamp",
  "Lineare Leuchte aus Aluminium": "Linear Aluminium Light",
  "Leuchtkörper mit Seidenschirm": "Light Object with Silk Shade",
  "Wandobjekt mit indirektem Licht": "Wall Object with Indirect Light",
  "Papierarbeit mit Struktur": "Structured Paper Work",
  "Mineralische Fläche auf Leinen": "Mineral Surface on Linen",
  "Kleine Bronzeplastik": "Small Bronze Sculpture",
  "Wandarbeit aus Papier": "Paper Wall Work",
  "Relief aus hellem Holz": "Light Wood Relief",
  "Arbeit mit Asche und Pigment": "Work with Ash and Pigment",
  "Textile Wandarbeit": "Textile Wall Work",
  "Objekt aus Stein und Papier": "Object in Stone and Paper",
  "Schwarze Zeichnung auf Bütten": "Black Drawing on Handmade Paper",
  "Skulptur aus gebranntem Ton": "Fired Clay Sculpture",
  "Diptychon mit feiner Linie": "Diptych with Fine Line",
  "Kleine Arbeit auf Holz": "Small Work on Wood",
  "Wollteppich in Naturtönen": "Wool Rug in Natural Tones",
  "Flacher Teppich aus Leinen": "Flat Linen Rug",
  "Handgeknüpfter Teppich in Grau": "Hand-Knotted Grey Rug",
  "Textile Fläche mit Relief": "Textile Surface with Relief",
  "Läufer aus ungefärbter Wolle": "Runner in Undyed Wool",
  "Teppich mit mineralischer Farbigkeit": "Rug with Mineral Colouring",
  "Runder Teppich in Naturweiß": "Round Natural White Rug",
  "Gewebter Teppich mit Kante": "Woven Rug with Edge Detail",
  "Teppich in dunkler Melange": "Dark Melange Rug",
  "Kleiner Teppich für Lesezone": "Small Rug for a Reading Area",
  "Große textile Raumfläche": "Large Textile Room Surface",
  "Wandteppich mit feinem Flor": "Wall Rug with Fine Pile",
  "Beistelltisch aus Naturstein": "Natural Stone Side Table",
  "Steinobjekt mit geschliffener Kante": "Stone Object with Polished Edge",
  "Bronzeform für den Tisch": "Bronze Table Form",
  "Keramikobjekt mit dunkler Glasur": "Ceramic Object with Dark Glaze",
  "Glasobjekt mit Einschluss": "Glass Object with Inclusion",
  "Kleine Skulptur aus Holz": "Small Wood Sculpture",
  "Objekt aus Messing und Stein": "Object in Brass and Stone",
  "Wandobjekt aus Keramik": "Ceramic Wall Object",
  "Schale aus Naturstein": "Natural Stone Bowl",
  "Objekt mit Grifföffnung": "Object with Handle Opening",
  "Kleine Metallarbeit": "Small Metal Work",
  "Sockelobjekt aus hellem Stein": "Plinth Object in Light Stone",
  "Keramikobjekt mit Grifföffnung": "Ceramic Object with Handle Opening",
  "Vase aus glasierter Keramik": "Vase in Glazed Ceramic",
  "Flache Schale aus Steinzeug": "Flat Stoneware Bowl",
  "Untersetzer aus Naturstein": "Natural Stone Coaster",
  "Kerzenhalter aus Ton": "Clay Candleholder",
  "Kleines Tablett aus Messing": "Small Brass Tray",
  "Glasbecher mit schwerem Boden": "Glass Tumbler with Heavy Base",
  "Servierschale mit matter Glasur": "Serving Bowl with Matte Glaze",
  "Objektvase in dunkler Glasur": "Object Vase with Dark Glaze",
  "Steinplatte für den Tisch": "Stone Plate for the Table",
  "Kleine Schale aus Bronze": "Small Bronze Bowl",
  "Keramikset mit drei Formen": "Ceramic Set with Three Forms",
  "Limitierter Beistelltisch aus Stein": "Limited Stone Side Table",
  "Sitzskulptur mit Stahlrahmen": "Seating Sculpture with Steel Frame",
  "Edition aus Bronze und Glas": "Edition in Bronze and Glass",
  "Objekttisch mit patinierter Fläche": "Object Table with Patinated Surface",
  "Keramische Sitzform": "Ceramic Seating Form",
  "Regalobjekt in kleiner Edition": "Shelf Object in a Small Edition",
  "Steinrelief als Objekt": "Stone Relief as Object",
  "Tischobjekt aus Holz und Bronze": "Table Object in Wood and Bronze",
  "Wandkonsole in limitierter Serie": "Wall Console in a Limited Series",
  "Sammelobjekt aus Keramik": "Collectible Ceramic Object",
  "Edition eines Raumobjekts": "Edition of a Room Object",
  "Kerzenhalter aus patinierter Bronze": "Candleholder in Patinated Bronze",
  "Kleine Edition aus Papier": "Small Paper Edition",
  "Bronzeobjekt in kleiner Auflage": "Bronze Object in a Small Edition",
  "Glasobjekt als Edition": "Glass Object as Edition",
  "Keramikedition mit matter Glasur": "Ceramic Edition with Matte Glaze",
  "Druck auf handgeschöpftem Papier": "Print on Handmade Paper",
  "Kleine Wandarbeit aus Holz": "Small Wood Wall Work",
  "Edition aus Naturstein": "Natural Stone Edition",
  "Objektset aus drei Formen": "Object Set with Three Forms",
  "Metallarbeit in kleiner Auflage": "Metal Work in a Small Edition",
  "Papierrelief als Edition": "Paper Relief as Edition",
  "Keramisches Wandstück": "Ceramic Wall Piece",
};

export function getEnglishProductTitle(title: string) {
  return englishProductTitles[title] ?? title;
}

export const translatedEnglishProductTitles = englishProductTitles;
